### ISSUE TITLE
Manpage links in wiki are broken

### ISSUE THREAD

**Issue by EdoardoLaGreca** [fvwmorg/fvwmorg.github.io#13]
Some (if not all) manpage links in the wiki are broken.

Examples of wiki pages with manpage links: [Syntax](https://www.fvwm.org/Wiki/Config/Syntax/), [Style](https://www.fvwm.org/Wiki/Config/Style/), [ColorSets](https://www.fvwm.org/Wiki/Config/Colorsets/).

Manpage links point to `http://fvwm.org/documentation/manpages/` and `http://fvwm.org/documentation/manpages/fvwm.html` but those pages do not exist (404).

**Comment by somiaj** [comment]
Thanks, I have removed the dead links in #14. Note fvwm3 now has the configure option `--enable-htmldoc` which will build html versions of the manual pages locally you can view if you prefer html versions over traditional manpages. The best manpages are the ones built for the version of fvwm you are running.

**Comment by EdoardoLaGreca** [comment]
Don't worry, I'm using FVWM 2.6.9 and I'm fine with the traditional manpages :)
