### ISSUE TITLE
Suggestion for /Wiki /CookBook

### ISSUE THREAD

**Issue by rasatpc** [fvwmorg/fvwmorg.github.io#18]
Before adding new recipes to CookBook, I am suggesting to categorize them as per the default config. It becomes easier for users to find them as well as contribute new recipes.
This screenshot is created in Gimp. The fonts and look may differ from the actual page. If accepted, I will modify the current CookBook page and PR.
https://rasatpc.net/screenshot/CookBook.png

**Comment by somiaj** [comment]
The way it is setup is to mirror the file structure, and I don't think at this time the cookbook needs to be split into multiple sub directories. Also I don't think the items fit as nicely into each of the categories as you have suggested. One alternative is adding tags to the items that could be used to help find. Here is an example.

![image](https://github.com/fvwmorg/fvwmorg.github.io/assets/18082412/4e6eda7b-00d6-4ae1-8172-31af66b7a4c2)

**Comment by somiaj** [comment]
Check out #19, this branch adds the ability to add tags as shown above to the different entries. I don't actually go and tag stuff (will leave that for you if you will like), I just added the tags feature, with the single AltTab example.

**Comment by rasatpc** [comment]
In my suggestion, there are no sub-directories but category labels. And the recipes sorted under them.
I like the tags, they become the same but cleaner. Also, a recipe can have more tags which often will be.

I am suggesting the tags mirror the file structure (functions, styles, etc.). This orderliness makes it easier to find where is what, and create configs. I have been using this structure for three years when creating individual scrips (configs).

**Comment by somiaj** [comment]
The tag feature has been added, you are welcome to make a PR adding tags to the various pages. They are straight forward to add.

**Comment by somiaj** [comment]
Tagging alternative was added in #19.
