### ISSUE TITLE
Broken wiki link

### ISSUE THREAD

**Issue by jidanni** [fvwmorg/fvwmorg.github.io#8]
Janon’s Simple Portable Configuration link on https://www.fvwm.org/Wiki/NewToFvwm/ is broken.

**Comment by ThomasAdam** [comment]
Hi @jidanni 

Thanks.  It will be as Janon sadly passed away.  Can you check if the content is available on the wayback machine?

**Comment by jidanni** [comment]
Alas my brush with fvwm only lasted 27 minutes,
https://bugs.chromium.org/p/chromium/issues/detail?id=1246668#c23
so I won't be checking soon.
